package org.freecash.domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Type;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

/**
 * 应用发布协议(fch_feip15)
 * 
 * @author bianj
 * @version 1.0.0 2020-09-10
 */
@Entity
@Table(name = "fch_feip17")
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Feip17 implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -2243111963502139952L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** ID */
    @Id
    @Column(name = "pid", unique = true, nullable = false,columnDefinition = "varchar(200) comment 'ID'")
    private String pid;

    /** 协议类型 */
    @Column(name = "protocol_type", columnDefinition = "varchar(200) comment '协议名称'")
    private String protocolType;

    /** 协议编号 */
    @Column(name = "protocol_no", columnDefinition = "varchar(200) comment '协议编号'")
    private String protocolNo;

    /** 版本号 */
    @Column(name = "protocol_version", columnDefinition = "varchar(200) comment '版本号'")
    private String protocolVersion;

    /** 算法 */
    @Column(name = "algorithm", columnDefinition = "varchar(200) comment '算法'")
    private String algorithm;

    /** 密文 */
    @Column(name = "cipher_text", columnDefinition = "varchar(200) comment '密文'")
    private String cipherText;

    /** 类型 */
    @Column(name = "type", columnDefinition = "varchar(200) comment '类型'")
    private String type;

    /** 备注 */
    @Column(name = "remarks", columnDefinition = "varchar(200) comment '备注'")
    private String remarks;

    /** 详情 */
    @Column(name = "tx_id", columnDefinition = "varchar(200) comment '详情'")
    private String txId;

    /** 创建者 */
    @Column(name = "cid", columnDefinition = "varchar(200) comment '创建者'")
    private String cid;

    /** 上链时间 */
    @Column(name = "online_date", columnDefinition = "varchar(200) comment '上链时间'")
    private String onLineDate;
}