btc:
  job:
    batch: 10000
    corn: 0 * * * * ?
    update:
      corn: 0 * * * * ?
      batch: 10000
rpc:
  protocol: http
  host: 111.229.195.222
  port: 34452
  user: darkcoinrpc
  password: 123gfjk3R3pCCVjHtbRde2s5kzdf233sa
  scheme: Basic
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://111.229.195.222:3306/freecash?charset=utf8mb4&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

logging:
  file: /root/docker/fch-sso/logs/sso.log
  root: debug

freecash:
  amount: 0.01
  address: FAxNcqAvdjMd9nhdzpggXn2Tu6khQTzjmr
  fee: 0.0001
  freedrive:
    put: http://freedrive.fchwallet.com:8442/api/put
    update: http://freedrive.fchwallet.com:8442/api/update
    get: http://freedrive.fchwallet.com:8442/api/get
    getDriveId: http://freedrive.fchwallet.com:8442/api/get_drive_id