btc:
  job:
    batch: 1000
    corn: 0 * * * * ?
    update:
      corn: 0/10 * * * * ?
      batch: 10000
    memUpdate:
      corn: 0/10 * * * * ?
      batch: 1000
rpc:
  protocol: http
  host: 172.17.0.1
  port: 34452
  user: darkcoinrpc
  password: 123gfjk3R3pCCVjHtbRde2s5kzdf233sa
  scheme: Basic
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://119.45.251.246:10000/freecash?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

logging:
  file: /root/docker/fch-sso/logs/sso.log
  root: debug

freecash:
  amount: 0.001
  address: FMsaesLKdiFc4co21X2w4LaRWcbaSEFzm6
  fee: 0.00005
  privkey: L1NDhDzQsK4sMDhvcVTPVU3T8Xx7NoPXKadGvyoXidDqXXTesjsR
  freeDrive:
    put: http://47.119.148.93:4001/v0/cavern/file/put
    get: http://47.119.148.93:4001/v0/cavern/file/get
    list: http://47.119.148.93:4001/v0/cavern/file/index
    check: http://47.119.148.93:4001/v0/cavern/file/check

file:
  path: /write/file/