btc:
  job:
    batch: 10000
    corn: 0 * * * * ?
    update:
      corn: 0/10 * * * * ?
      batch: 1000
    memUpdate:
      corn: 0/10 * * * * ?
      batch: 1000
rpc:
  protocol: http
  host: 127.0.0.1
  port: 34452
  user: darkcoinrpc
  password: 123gfjk3R3pCCVjHtbRde2s5kzdf233sa
  scheme: Basic

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tbl?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

logging:
  file: e:/log/core.log
  root: DEBUG

freecash:
  amount: 0.001
  address: FMsaesLKdiFc4co21X2w4LaRWcbaSEFzm6
  fee: 0.00005
  privkey: L1NDhDzQsK4sMDhvcVTPVU3T8Xx7NoPXKadGvyoXidDqXXTesjsR
  freedrive:
    put: https://open.api.qingniao.cloud/api/put
    get: https://open.api.qingniao.cloud/api/get
    list: https://open.api.qingniao.cloud/api/list
    get_drive_info: https://open.api.qingniao.cloud/api/get_drive_info
    auth: https://open.api.qingniao.cloud/api/auth
  protocols:
    - FIPA1
    - FIPA2
    - FEIP1
    - FEIP2
    - FEIP3
    - FEIP4
    - FEIP5
    - FEIP6
    - FEIP7
    - FEIP8
    - FEIP9
    - FEIP10
    - FEIP11
    - FEIP12
    - FEIP15
    - FEIP16
    - FOCP1
    - FOCP2
    - FOCP3
    - FOCP4
    - FOCP5